name: 'Github Actions to Docker Swarm'
description: 'Simple docker swarm service updater like portainer webhooks'
inputs:
  serviceId:
    description: 'The ID of the service'
    required: true
  imageTag:
    description: 'The Docker image tag'
    required: false
  dockerOptions:
    description: 'JSON connection options (dockerode)'
    required: true
  privateKeyPath:
    description: 'ssh private key path'
    required: false
  privateKey:
    description: 'ssh private key'
    required: false
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'upload-cloud'
  color: 'blue'
